# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv")

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [9]:
df1 = df.iloc[:, :12]
df1

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that will capitalize strings.

In [10]:
kapital = lambda x : str.capitalize(x)

### Step 6. Capitalize both Mjob and Fjob

In [14]:
df['Mjob'] = df['Mjob'].apply(kapital)
df['Mjob']

0       At_home
1       At_home
2       At_home
3        Health
4         Other
         ...
390    Services
391    Services
392       Other
393    Services
394       Other
Name: Mjob, Length: 395, dtype: object

In [16]:
df['Fjob'] = df['Fjob'].apply(kapital)
df['Fjob']

0       Teacher
1         Other
2         Other
3      Services
4         Other
         ...
390    Services
391    Services
392       Other
393       Other
394     At_home
Name: Fjob, Length: 395, dtype: object

### Step 7. Print the last elements of the data set.

In [17]:
df.iloc[-1, -1]

np.int64(9)

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [18]:
df['Mjob'] = df['Mjob'].apply(kapital)
df['Fjob'] = df['Fjob'].apply(kapital)

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [22]:
def majority(x):
  if(x >17):
    return True
  else :
    return False

In [28]:
df1['legal_drinker'] = df1['age'].apply(majority)
df1.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,True
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,False
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,False
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,False

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [29]:
df1 * 10

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,180,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,AAAAAAAAAA,40,40,at_homeat_homeat_homeat_homeat_homeat_homeat_h...,teacherteacherteacherteacherteacherteacherteac...,coursecoursecoursecoursecoursecoursecoursecour...,mothermothermothermothermothermothermothermoth...,10
1,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,170,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,10,10,at_homeat_homeat_homeat_homeat_homeat_homeat_h...,otherotherotherotherotherotherotherotherothero...,coursecoursecoursecoursecoursecoursecoursecour...,fatherfatherfatherfatherfatherfatherfatherfath...,0
2,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,150,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,10,10,at_homeat_homeat_homeat_homeat_homeat_homeat_h...,otherotherotherotherotherotherotherotherothero...,otherotherotherotherotherotherotherotherothero...,mothermothermothermothermothermothermothermoth...,0
3,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,150,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,40,20,healthhealthhealthhealthhealthhealthhealthheal...,servicesservicesservicesservicesservicesservic...,homehomehomehomehomehomehomehomehomehome,mothermothermothermothermothermothermothermoth...,0
4,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,160,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,30,30,otherotherotherotherotherotherotherotherothero...,otherotherotherotherotherotherotherotherothero...,homehomehomehomehomehomehomehomehomehome,fatherfatherfatherfatherfatherfatherfatherfath...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,200,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,AAAAAAAAAA,20,20,servicesservicesservicesservicesservicesservic...,servicesservicesservicesservicesservicesservic...,coursecoursecoursecoursecoursecoursecoursecour...,otherotherotherotherotherotherotherotherothero...,10
391,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,170,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,30,10,servicesservicesservicesservicesservicesservic...,servicesservicesservicesservicesservicesservic...,coursecoursecoursecoursecoursecoursecoursecour...,mothermothermothermothermothermothermothermoth...,0
392,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,210,RRRRRRRRRR,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,10,10,otherotherotherotherotherotherotherotherothero...,otherotherotherotherotherotherotherotherothero...,coursecoursecoursecoursecoursecoursecoursecour...,otherotherotherotherotherotherotherotherothero...,10
393,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,180,RRRRRRRRRR,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,30,20,servicesservicesservicesservicesservicesservic...,otherotherotherotherotherotherotherotherothero...,coursecoursecoursecoursecoursecoursecoursecour...,mothermothermothermothermothermothermothermoth...,10
394,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,190,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,10,10,otherotherotherotherotherotherotherotherothero...,at_homeat_homeat_homeat_homeat_homeat_homeat_h...,coursecoursecoursecoursecoursecoursecoursecour...,fatherfatherfatherfatherfatherfatherfatherfath...,10

In [38]:
df1.select_dtypes(include = 'number').apply(lambda x : x*10)

     age  Medu  Fedu
0    180    40    40
1    170    10    10
2    150    10    10
3    150    40    20
4    160    30    30
..   ...   ...   ...
390  200    20    20
391  170    30    10
392  210    10    10
393  180    30    20
394  190    10    10

[395 rows x 3 columns]