# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
a = np.random.randint(1, 4, 100)
b = np.random.randint(1, 3, 100)
c = np.random.randint(10000, 30000, 100)

### Step 3. Let's create a DataFrame by joinning the Series by column

In [7]:
df = pd.DataFrame([a, b, c]).T
df

    0  1      2
0   2  2  29833
1   1  1  20108
2   3  1  25746
3   2  1  27606
4   1  2  24870
.. .. ..    ...
95  3  2  17600
96  1  1  12736
97  3  1  12797
98  1  1  10906
99  3  2  19718

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [10]:
df.columns = ['bedrs', 'bathrs', 'price_sqr_meter']

In [11]:
df

    bedrs  bathrs  price_sqr_meter
0       2       2            29833
1       1       1            20108
2       3       1            25746
3       2       1            27606
4       1       2            24870
..    ...     ...              ...
95      3       2            17600
96      1       1            12736
97      3       1            12797
98      1       1            10906
99      3       2            19718

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [20]:
bigcolumn = pd.concat([pd.Series(a), pd.Series(b), pd.Series(c)]).to_frame()

In [21]:
bigcolumn

        0
0       2
1       1
2       3
3       2
4       1
..    ...
95  17600
96  12736
97  12797
98  10906
99  19718

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [22]:
bigcolumn.size

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [24]:
bigcolumn.reset_index()

     index      0
0        0      2
1        1      1
2        2      3
3        3      2
4        4      1
..     ...    ...
295     95  17600
296     96  12736
297     97  12797
298     98  10906
299     99  19718

[300 rows x 2 columns]