# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [5]:
raw_data = {"name" : ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
            'evolution' : ['Ivyasaur', 'Charmeleon', 'wartortle', 'Metapod'],
            'hp' : [45, 39, 44, 45],
            'type' : ['grass', 'fire', 'water', 'bug'],
            'pokedex' : ['yes', 'no', 'yes', 'no'],
            }

### Step 3. Assign it to a variable called pokemon

In [6]:
pokemon = pd.DataFrame(raw_data)
pokemon

         name   evolution  hp   type pokedex
0   Bulbasaur    Ivyasaur  45  grass     yes
1  Charmander  Charmeleon  39   fire      no
2    Squirtle   wartortle  44  water     yes
3    Caterpie     Metapod  45    bug      no

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [7]:
pokemon = pokemon[['name', 'type', 'hp', 'evolution','pokedex']]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45    Ivyasaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [9]:
pokemon.loc[:, 'place'] = ['Nias', 'Banyuwangi', 'Jakarta', 'Sunda']
pokemon

/tmp/ipykernel_2908/1393281539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pokemon['place'] = ['Nias', 'Banyuwangi', 'Jakarta', 'Sunda']

         name   type  hp   evolution pokedex       place
0   Bulbasaur  grass  45    Ivyasaur     yes        Nias
1  Charmander   fire  39  Charmeleon      no  Banyuwangi
2    Squirtle  water  44   wartortle     yes     Jakarta
3    Caterpie    bug  45     Metapod      no       Sunda

### Step 6. Present the type of each column

In [10]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
pokedex      object
place        object
dtype: object

### BONUS: Create your own question and answer it.